2025-07-29 16:36:59.580 | INFO     | __main__:main:37 - Starting FAISS index build process
2025-07-29 16:36:59.580 | INFO     | __main__:main:50 - Initializing SFDC client...
2025-07-29 16:36:59.580 | INFO     | src.data_extraction.sfdc_client:_connect:34 - Connecting to Salesforce with:
2025-07-29 16:36:59.580 | INFO     | src.data_extraction.sfdc_client:_connect:35 -   Username: jaykarki@algo.com
2025-07-29 16:36:59.580 | INFO     | src.data_extraction.sfdc_client:_connect:36 -   Login URL: https://login.salesforce.com
2025-07-29 16:36:59.580 | INFO     | src.data_extraction.sfdc_client:_connect:37 -   Domain: login
2025-07-29 16:36:59.580 | INFO     | src.data_extraction.sfdc_client:_connect:38 -   API Version: 58.0
2025-07-29 16:36:59.580 | INFO     | src.data_extraction.sfdc_client:_connect:39 -   Security Token: ************************
2025-07-29 16:37:01.000 | INFO     | src.data_extraction.sfdc_client:_connect:49 - Successfully connected to Salesforce
2025-07-29 16:37:01.345 | INFO     | src.data_extraction.sfdc_client:test_connection:220 - Salesforce connection test successful
2025-07-29 16:37:01.346 | INFO     | __main__:main:58 - Initializing text processor...
2025-07-29 16:37:01.346 | INFO     | __main__:main:61 - Initializing vector database...
2025-07-29 16:37:01.346 | INFO     | __main__:main:65 - Extracting case data from Salesforce...
2025-07-29 16:37:01.711 | ERROR    | src.data_extraction.sfdc_client:get_case_data_batch:135 - Error in batch extraction: Malformed request https://algoleap-5e-dev-ed.develop.my.salesforce.com/services/data/v58.0/query/?q=%0A++++++++SELECT+Origin%2C+Id%2C+Priority%2C+Reason%2C+Subject_description__c%2C+Description%2C+Issue__c%2C+Cause_plain_text__c%2C+Resulution_plain_text__c%2C+CreatedDate%2C+Status%2C+CaseNumber%2C+Type%2C+LastModifiedDate%2C+BodyText__c%0A++++++++FROM+Case+%0A++++++++WHERE+CreatedDate+%3E%3D+2023-07-30T16%3A37%3A01.000%2B0000+%0A++++++++++AND+CreatedDate+%3C%3D+2025-07-29T16%3A37%3A01.000%2B0000%0A++++++++++AND+Status+%21%3D+%27Deleted%27%0A++++++++ORDER+BY+CreatedDate+DESC%0A++++++++. Response content: [{'message': "\nOrigin, Id, Priority, Reason, Subject_description__c, Description\n                              ^\nERROR at Row:1:Column:38\nNo such column 'Subject_description__c' on entity 'Case'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.", 'errorCode': 'INVALID_FIELD'}]
2025-07-29 16:37:01.712 | ERROR    | __main__:main:142 - Error during index build: Malformed request https://algoleap-5e-dev-ed.develop.my.salesforce.com/services/data/v58.0/query/?q=%0A++++++++SELECT+Origin%2C+Id%2C+Priority%2C+Reason%2C+Subject_description__c%2C+Description%2C+Issue__c%2C+Cause_plain_text__c%2C+Resulution_plain_text__c%2C+CreatedDate%2C+Status%2C+CaseNumber%2C+Type%2C+LastModifiedDate%2C+BodyText__c%0A++++++++FROM+Case+%0A++++++++WHERE+CreatedDate+%3E%3D+2023-07-30T16%3A37%3A01.000%2B0000+%0A++++++++++AND+CreatedDate+%3C%3D+2025-07-29T16%3A37%3A01.000%2B0000%0A++++++++++AND+Status+%21%3D+%27Deleted%27%0A++++++++ORDER+BY+CreatedDate+DESC%0A++++++++. Response content: [{'message': "\nOrigin, Id, Priority, Reason, Subject_description__c, Description\n                              ^\nERROR at Row:1:Column:38\nNo such column 'Subject_description__c' on entity 'Case'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.", 'errorCode': 'INVALID_FIELD'}]
